### ISSUE TITLE
Add the section on MarkDown right after the Python review section (see comments for more details)

### ISSUE THREAD

**Issue by uhzees** [pearcej/httlads#101]
- [ ] Add this page right after the Python review pages of the same chapter: 

Markdown Cells
Notebook interface is a virtual environment that resembles a real-life research notebook. A form of Literate Programming, it allows for the possibility of not only writing code but also inspecting and documenting its results as a piece of literature understandable for human beings. As you will learn later, the only way to document anything in a pure code environment is to use comments and docstrings, which is not convenient for Data Scientists interested in reproducible research and open access for everyone, even its non-technical users. So, a great advantage of a Notebook environment is being able to combine both code and nicely formatted text or graphics to easily document your flows. 
The industry standard of a Notebook environment is Jupyter Notebook, a free, open-source interactive web-based computational Notebook. Though computational notebooks existed long before Jupyter Notebook, its multi-language programming capabilities are what made it the industry standard. Even its name, Jupyter, is an acronym for all of its coding languages - Julia, Python, and R. Currently, there are many Notebook environments for the users to choose from. In this book, we will highlight Google Colab as an installation-free, cloud-based version of a Notebook environment.
There are two types of cells in Notebooks: code cells and text cells. One of the differences between the two types of cells is their variety. While code cells will vary in their format based on the programming language used, the text cells will always use a universally recognized text format language known as Markdown.
Markdown is a lightweight Markup (human-readable syntax) language that many consider being a key authoring framework for data science. Markdown allows for capabilities like bolding, italicizing, or making headers just like word processing tools Google Docs or Microsoft Word.
Markdown Cells are run in the same way as Code Cells by pressing on the Run button or holding Shift + Return keys. Outside of Notebooks, you can use Markdown to create a web page, pdf, MS Word document, slide show, and a whole host of other file types.
To learn more about Jupyter Notebook installation and instructions for use, see Appendix {number}. To learn more about Google Collab, a similar cloud-based Notebook that will not require any installations on your computer, see Appendix {number}.

Google Doc: https://docs.google.com/document/d/1ytJwV40iOiA8U16LVfJaQWdkCnh3nNbKldzzjknNNOY/edit?usp=sharing

**Comment by belainehi** [comment]
Sandesh and I are working on this.

**Comment by Sandesh-L** [comment]
Resolved in PR #159
