### ISSUE TITLE
Chapter-2-I-S  link for world_countries_2019.csv needs a fix

### ISSUE THREAD

**Issue by belainehi** [pearcej/httlads#106]
All branches: Chapter-2-I-S-fixes and other branches descended from this branch also need the fix.

**Comment by belainehi** [comment]
Resolved on PR #107 .

**Comment by WhitfordR** [comment]
I fixed this on the Chapter-2-I-S-fixes branch, which I will make a pull request for when all the other issues related to it have been resolved.
