### ISSUE TITLE
Change the images in chapter 3 to reference Solver instead of OpenSolver

### ISSUE THREAD

**Issue by WhitfordR** [pearcej/httlads#18]
Since Opensolver is no longer an available tool we will have to use Solver instead, and the instructions in chapter three need to be updated accordingly. The images in chapter three are currently pictures of the Opensolver interface, and need to show the Solver interface instead.

**Comment by belainehi** [comment]
Sandesh and I are working on this.

**Comment by Sandesh-L** [comment]
Resolver in Pull Request #53
