### ISSUE TITLE
Change text in chapter three to reference Solver instead of OpenSolver

### ISSUE THREAD

**Issue by WhitfordR** [pearcej/httlads#29]
Opensolver is no longer a usable tool, so we are now using Solver instead. Solver mostly works equivalently to how Opensolver worked, but all the text that references Opensolver now needs to be changed to reference Solver, and the problems need to be checked through Solver to make sure that the process is the same. If anything is different it should be changed to be accurate to Solver instead of Opensolver.

**Comment by belainehi** [comment]
Sandesh and I resolved this on PR #54 .
