### ISSUE TITLE
Add a chapter on python before python is needed in the book

### ISSUE THREAD

**Issue by WhitfordR** [pearcej/httlads#61]
Since the book will be used for students who do not necessarily have any background in python, python needs to be introduced before it is used as a tool in later chapters.

**Comment by belainehi** [comment]
#chapter 4 needs to be fleshed out more to provide a solid introduction to Python and teach students new to it all they need to know about python to use it for the rest of the book. This can be done by using rst Files for Chapter 1.8 & 1.9 of PythonDS into the httldads book #61
