### ISSUE TITLE
Change existing inputs, 'global warming' and 'climate change' to ‘income’ and ‘interest rate’ as their inputs, and make appropriate changes to the parts related to it 8.1.3

### ISSUE THREAD

**Issue by uhzees** [pearcej/httlads#90]
1. The following part needs to be updated:
![Screen Shot 2020-07-03 at 10 20 46 AM](https://user-images.githubusercontent.com/42677564/86479416-1f4a8c00-bd1a-11ea-9bc7-730fe08b279f.png)

2. Update the text and the graphs to make sense of the change

**Comment by belainehi** [comment]
Sandesh and I are working on this now.

**Comment by Sandesh-L** [comment]
Resolved in PR #102
